version: 2
updates:
  - package-ecosystem: "yarn"
    directory: "/"
    schedule:
      interval: "monthly"  # You can change it to "daily" or "monthly" depending on your preference
    versioning-strategy: "increase"  # Options: "increase", "lockfile-only", "auto"
